
name: TESTES

on:
  push:
    branches:
      -master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Npm install
      run: npm install jest
    - name: Execute Jest
      run: npm run test
